import modals from "./modules/modals";
import sliders from "./modules/sliders";
import formsFn from "./modules/forms";
import mask from "./modules/mask";
import showMoreStyles from "./modules/showMoreStyles";
import checkTextInInputs from "./modules/checkTextInInput";
import showStylesFromServer from "./modules/showStylesFromServer";
import calculate from "./modules/calculate";
import filter from "./modules/filter";
import { indentifierBrowser } from "./modules/modals";
window.addEventListener("DOMContentLoaded", () => {
    "use strict";
    indentifierBrowser();
    modals();
    sliders('.feedback-slider-item', 'horizontal', '.main-prev-btn', '.main-next-btn');
    sliders('.main-slider-item', 'vertical');
    formsFn();
    mask('[name="phone"]');
    checkTextInInputs('[name="name"]');
    checkTextInInputs('[name="message"]');
    //showMoreStyles('.styles-2', '.button-styles');
    showStylesFromServer('#styles .row', '.button-styles');
    calculate('#size', '#material', '#options', '.promocode', '.calc-price');
    filter();
});